# Generated by Django 5.2.6 on 2025-09-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('status', models.CharField(choices=[('to_do', 'TO DO'), ('in_progress', 'INPROGRESS'), ('done', 'DONE')])),
                ('priority', models.CharField(choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, max_length=400)),
                ('deadLine', models.DateField(blank=True)),
                ('progress', models.DecimalField(decimal_places=1, max_digits=2)),
                ('assigned_to', models.CharField()),
            ],
        ),
    ]
