# Generated by Django 5.2.6 on 2025-09-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('to_do', 'TO DO'), ('in_progress', 'INPROGRESS'), ('done', 'DONE')], default='to_do', max_length=50)),
                ('priority', models.CharField(choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')], default='high', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, max_length=400, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('progress', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TaskModel',
        ),
    ]
