# Generated by Django 5.2.6 on 2025-09-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_delete_taskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.CharField(blank=True),
        ),
    ]
