# Generated by Django 5.2.6 on 2025-09-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('role', models.CharField(choices=[('1', 'employee'), ('2', 'manager'), ('3', 'HR'), ('4', 'admin')])),
                ('department', models.TextField(max_length=100)),
                ('avatar', models.TextField(max_length=100)),
                ('bio', models.TextField(max_length=1000)),
            ],
        ),
    ]
